jobs:
  uberjar:
    name: Build uberjar
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        build:
          traits:
            'OpenJDK': true
          scripts:
            uberjar:
              body: |
                set -eux
                git submodule update --init --recursive --force
                ./bin/clj-uberjar
