jobs:
  uberjar:
    name: Build uberjar
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        build:
          traits:
            asdf: true
          scripts:
            uberjar:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                git submodule update --init --recursive --force
                ./bin/clj-uberjar
